api = "0.2"

[buildpack]
  id = "andymoe/deno-buildpack"
  name = "Deno buildpack"
  homepage = "https://github.com/andymoe/deno-buildpack"
  version = "0.0.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  [[metadata.dependencies]]
    uri = "https://github.com/denoland/deno/releases/download/v1.4.4/deno-x86_64-unknown-linux-gnu.zip"