api = "0.2"

[buildpack]
  id = "andymoe/deno-buildpack"
  name = "Deno buildpack"
  homepage = "https://github.com/andymoe/deno-buildpack"
  version = "0.0.1"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"